assets:
  rubygems.yml: "yegor256/home#assets/rubygems.yml"
  s3cfg: "yegor256/home#assets/s3cfg"

install: |
  sudo gem install pdd
  sudo apt-get install -y subversion diffstat

release:
  script: |
    sudo bundle install
    rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/hoc/version.rb
    gem build hoc.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
    pdd --source=$(pwd) --verbose --file=hoc.xml
    s3cmd --no-progress put hoc.xml --config=../s3cfg s3://pdd.teamed.io/hoc.xml
