language: ruby
cache: bundler
branches:
  only:
    - master
install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y diffstat
  - travis_retry sudo apt-get remove -y subversion
  - travis_retry sudo apt-get install -y subversion
  - travis_retry bundle install
script:
  - rake

