language: ruby
cache: bundler
branches:
  only:
    - master
install:
  - sudo apt-get update
  - travis_retry sudo apt-get install -y --fix-missing diffstat
  - travis_retry bundle install
script:
  - rake

